### PR TITLE
Propagate chunksize keyword argument

### PR DESCRIPTION
**Pull request by ddelange**
Supersedes and closes #198

### CODE REVIEW

**Comment by ddelange** [comment]
Hi @mmckerns 👋 do you have a rough ETA for this one and #252?

**Comment by mmckerns** [comment]
Currently it's on my calendar for early December, and it will definitely go into the next release.  I've been  a bit backlogged due to proposal season, but should get to it soon.

**Comment by ddelange** [comment]
Thanks for the quick reply! Good luck 💪

**Comment by mmckerns** [comment]
changes from your PR was significant enough that I just went ahead with a new one and closed this one

**Pull request closed without merging**
